### PR TITLE
:memo: conventional NPM badge :rose:

### PR DESCRIPTION
**Pull request by basarat**

### CODE REVIEW

**Comment by kataras** [comment]
Thanks you! I will re-write  the whole readme, this was my first nodejs module:P

**Comment by basarat** [comment]
Just curious why you went with GPL. It makes it impossible to use this in a commercial project. Its okay if you want to keep it that way (its your project, do what you want!). But just wanted you to be aware of a potential blocker for significant adoption :rose:

**Comment by kataras** [comment]
Yes you are right, I though it myself yeserday, what's  about Apache License, is this ok? At first days I wanted gpl for use only on open source or no commercial projects
 but now I don't care :P

**Comment by basarat** [comment]
> what's about Apache License is this the same as gpl? or is this ok

Apache is *definitely okay*. 

Personally : I just go with MIT all things as a brain default.

**Comment by kataras** [comment]
Thanks you basarat for all, I'm learning programming from my 14th years ( I'm 22 now)  I never have any help from someone, thanks you :)

**Pull request merged**
